# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Pull Request Checker

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
          java-package: jdk
          architecture: x64
      - name: Codestyle Check
        run: mvn -B spotless:check compile --errors